### PR TITLE
Java problem 16

### LINKED ISSUE #52: Add "Factorial Digit Sum" Java Problem
## Issue Description:
This proposes adding the Factorial Digit Sum problem to our Java code repository.

## Problem Statement
You can find the problem statement [here](https://projecteuler.net/problem=20)

## Implementation
Please read [Contributing to Java Problems](https://github.com/SST-OSS/club-onboarding/blob/main/javaProblems/readme.md) to get started with how to create new java problem and test for the same.

### PR DESCRIPTION
**Pull request by abhinav26966**
This fixes  #52 and adds solution to `problem16` in javaProblems folder.

### CODE REVIEW

**Review by AbhinavGupta-de — CHANGES_REQUESTED** [review]
Try to add minimum number of commits in a single PR.

**Comment by AbhinavGupta-de** [comment]
Please make a new branch, solve the question again and then send the PR again

**Comment by Diwakar-Gupta** [comment]
@abhinav26966 You can also squash all the commits to a single one.
Also we add solution in file `Solution.java`  please follow the same pattern.

**Comment by AbhinavGupta-de** [comment]
Due to inactivity, I am closing this now.

**Pull request closed without merging**
