### PR TITLE
fixed directory structure removed unneeded problem24 from root directory

### PR DESCRIPTION
**Pull request by 2k4sm**
PR #76 accidentally added problem24 to root folder.
This commit fixes this by removing it from the root directory.

### CODE REVIEW

**Comment by Diwakar-Gupta** [comment]
We can also revert that pr, let's try that first

**Comment by 2k4sm** [comment]
That pr contained 2 folder insertions one inserted it into the Java problems folder and other into the root. so I decided doing a new pr which only removes the insertion into root folder will be good.

**Comment by 2k4sm** [comment]
> We can also revert that pr, let's try that first

That pr contained 2 folder insertions one inserted it into the Java problems folder and other into the root. so I decided doing a new pr which only removes the insertion into root folder will be good.

**Comment by Diwakar-Gupta** [comment]
make sense.

**Review by Diwakar-Gupta — APPROVED** [review]
In that case we r good to go

**Pull request merged**
